
#nombre = input("Ingrese su nombre:")
#edad = int(input("Ingresa tu edad:"))
#num1 = int(input ("ingresa un número:"))
#num2 = int(input ("ingresa otro número:"))
#anio_nacimiento = int(input("Ingresa tu año de nacimiento:"))
#precio_producto = int(input("Ingrese el precio de su prodcucto:"))
#cantidad_producto = float(input("¿Cuánto de ese prodcuto compró?:"))
#num3 = int(input("Ingrese un número entero:"))
#num4 = int(input("Ingrese un número entero:"))
#num5 = int(input("Ingrese el segundo número:"))

#print (nombre)
#print (f"el doble de edad edad es {edad*2}")
#print (f"La suma de los dos número que elegiste es : {num1+num2}")
#print (f"Tu edad es:{2025 - anio_nacimiento}")
#print (f"Su total es de ${precio_producto*cantidad_producto}")
#print (f"el cuadrado de ese número es {num3**2}")
#print (f"el promedio de ese número es de {(num4+num5)/2}")
#print (f"Hola, {nombre}. Tienes {edad} años")